### ISSUE TITLE
Not usable

### ISSUE THREAD

**Issue by i-public** [codevise/pageflow-linkmap-page#1]
Hello.

I tried to install this plugin but get stuck with an error:

> Could not find gem 'pageflow-linkmap-page (>= 0) ruby' in the gems avaiable on this machine

This appears after I changed all the files (Gemfile, pageflow.rb, js, css, etc) and run 'bundle install'

I also run 'bundle update pageflow' to get the newest version (0.9.1), but nothing worked.

Is there some magic we have to do in order to get it running?

Strange thing: this gem has no known version on github, could this be?

Regards, Johannes

**Comment by tf** [comment]
Hi,

this gem depends on features of the yet unreleased Pageflow 0.10 version. I could therefore not push it to rubygems so far. You will either have to use Pageflow from master or wait for the release of 0.10 which is planned for the first half of January. 

Tim

**Comment by tf** [comment]
`pageflow-linkmap-page 0.1` and `pageflow 0.10` are now available on rubygems.
