### ISSUE TITLE
Migration not included?

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow-linkmap-page#2]
When I try this plugin I get this error:

```
ActionView::Template::Error: Mysql2::Error: Table 'storyboard_production.pageflow_sites' doesn't exist: SHOW FULL FIELDS FROM `pageflow_sites`
```

I can't find the migration quickly. Is it somewhere else?

**Comment by tf** [comment]
Hi Joost,

At the moment `pageflow-linkmap-page` has a hard dependency on  `pageflow-external-links` to provide external link hotspots. There we have a migration for `pageflow_external_links_sites`. I'm a bit surprised it asks for `pageflow_sites` here. Is the external links gem installed? Can you provide a stack trace?

**Comment by tilsammans** [comment]
That's it then. I didn't have `pageflow-external-links` and as a result could not copy the migrations, because that gem wasn't activated. Added it and that seems to have done the trick.

I will send you the stack trace tonight.

**Comment by tf** [comment]
We should probably also add a note to the README saying that the gem needs to be installed since there are additional manual steps involved.

**Comment by tilsammans** [comment]
I'll submit a pull request for it.

**Comment by tilsammans** [comment]
[Here is the backtrace](https://gist.github.com/tilsammans/570dce18f696af0887f2210c4bad6755) as you can see, it has `pageflow-linkmap-page-0.1.0` quite visibly in there.

**Comment by tf** [comment]
Looks like Rails tries different module name combinations to find an adequate table. When it does not find one, it only reports the last one it tried.
