### ISSUE TITLE
Field of view adjust doesn't work

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow-linkmap-page#6]
When I click the 'Adjust Field of View' button for an external site thumbnail, nothing happens and this is shown in the console:

```
TypeError: this.model.getFilePosition is not a function. (In 'this.model.getFilePosition(this.options.propertyName,"y")', 'this.model.getFilePosition' is undefined)
```

**Comment by tf** [comment]
This is a valid issue, but it is not related to the linkmap page. Can you reopen in [`pageflow-external-links`](https://github.com/codevise/pageflow-external-links).
